# Generated by Django 2.0.1 on 2018-01-18 18:07

from django.db import migrations


def create_subjects(apps, schema_editor):
    Subject = apps.get_model('reqs', 'Subject')
    Subject.objects.create(name='Research 2', color='#343a40')
    Subject.objects.create(name='CS 5', color='#007bff')
    Subject.objects.create(name='Math 5', color='#28a745')
    Subject.objects.create(name='Biology 3', color='#17a2b8')
    Subject.objects.create(name='Physics 3', color='#ffc107')


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_subjects),
    ]
